# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Tooller

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  NUGET_REPO_URL: https://nuget.pkg.github.com/SergKorol/index.json

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '9.0.x' ]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    -- name: Release
      run: dotnet build --no-restore --configuration Release
    - name: Create the package
      run: dotnet pack --configuration Release Tooller.InterfaceGenerator/Tooller.InterfaceGenerator.csproj -p:TargetFramework=netstandard2.0
    ##- name: Publish the package to Repository
      ##run: dotnet nuget push Tooller.Interface/bin/Release/*.nupkg -k ${{ secrets.GH_TOKEN }} -s $NUGET_REPO_URL --skip-duplicate
    - name: Publish to NuGet.org
      run: dotnet nuget push Tooller.InterfaceGenerator/bin/Release/*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
